"""add column is_wait_confirm in Supply

Revision ID: b6078e83cd5f
Revises: 22ae89e147e1
Create Date: 2025-05-02 02:25:49.407032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6078e83cd5f"
down_revision: Union[str, None] = "22ae89e147e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplys", sa.Column("is_wait_confirm", sa.Boolean(), nullable=False)
    )
    op.drop_column("supplys", "is_cancelled")
    op.drop_column("supplys", "is_assembled")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplys",
        sa.Column(
            "is_assembled", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "supplys",
        sa.Column(
            "is_cancelled", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("supplys", "is_wait_confirm")
    # ### end Alembic commands ###
